<a href="https://colab.research.google.com/github/PRihana/Machine-learning/blob/master/17_03_2020(ML_)List_comprehensions_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
l1=[4,67,8,9]
l2=[1,2,3,4]
#o/p:[5,69,11,13]
out=[]
for i in range(len(l1)):
  out.append(l1[i]+l2[i])
out  

[5, 69, 11, 13]

In [0]:
out=[l1[i]+l2[i]  for i in range(len(l1))]
out

[5, 69, 11, 13]

In [0]:
#get the numbers which are not multiple of 3 as a list using
#list comprehension
mul3=[i for i in out if i%3!=0]
mul3

[5, 11, 13]

In [0]:
#replace the multiples of 3 with -1
out1=[i if i%3!=0 else -1 for i in out]
out1

[5, -1, 11, 13]

In [0]:
out.extend([2,8,9,6])

In [0]:
out

[5, 69, 11, 13, 2, 8, 9, 6]

In [0]:
#replace multiples of 2 with -2
#replace multiples of 3 with -1
#if it is a multiple of both replace it with -2
out1=[]
for i in out:
  if i%2==0:
    out1.append(-2)
  elif i%3==0:
    out1.append(-1)  
  else:
    out1.append(i)
print(out1)
print(out)
out2=[-2 if i%2==0 else -1 if i%3==0 else i for i in out]
print(out2)      

[5, -1, 11, 13, -2, -2, -1, -2]
[5, 69, 11, 13, 2, 8, 9, 6]
[5, -1, 11, 13, -2, -2, -1, -2]


#List comprehension with nested for:

In [0]:
l1,l2

([4, 67, 8, 9], [1, 2, 3, 4])

In [0]:
out=[]
for i in l1:#4
    for j in l2:#1,2,3,4
         out.append((i,j))
out         


[(4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (67, 1),
 (67, 2),
 (67, 3),
 (67, 4),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4)]

In [0]:
numbers=[(i,j) for i in l1 for j in l2]
numbers

[(4, 1),
 (4, 2),
 (4, 3),
 (4, 4),
 (67, 1),
 (67, 2),
 (67, 3),
 (67, 4),
 (8, 1),
 (8, 2),
 (8, 3),
 (8, 4),
 (9, 1),
 (9, 2),
 (9, 3),
 (9, 4)]

In [0]:
l2=[[23,45],[78,96],[56,12]]
#o/p:[23,45,78,96,56,12]
out2=[i for j in l2 for i in j]
out2

[23, 45, 78, 96, 56, 12]

In [0]:
#common elements in two lists using list comprehension
l3=list(range(5,20,2))
l4=list(range(1,20,2))
print(l3,l4)

[5, 7, 9, 11, 13, 15, 17, 19] [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [0]:
l3=list(range(5,20,2))
l4=list(range(1,20,2))
print(l3,l4)
[i for i in l3 for j in l4 if i==j]

[5, 7, 9, 11, 13, 15, 17, 19] [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


[5, 7, 9, 11, 13, 15, 17, 19]

#Numpy



*   numerical python
*   vectorized programming
*   handling multidimentoal data
*   manipulating arrays
*   We can define the datatype

*   Commonly used with numerical data. But you may use mixed data as well

*   Faster execution

*   Less Memory

*  Most of the mathematical functions are availbl

      -   linear Algebra
      -   statistics
      -   probability
      -   Fourier transform
      -   Trigonometric
      -   Logarithemic
      -   Exponential 


In [0]:
#version
import numpy
numpy.__version__ #attribute "__" - dunder

'1.18.1'

In [0]:
#importing a package with ailas name
import numpy as np

#Converting existing data into numpy array

In [0]:
l=[7,9,0,3,4]
array_1d=np.array(l)
print(type(array_1d))
print(array_1d)

<class 'numpy.ndarray'>
[7 9 0 3 4]


In [0]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [0]:
t=(7,9,0,3,4)
array_ld=np.array(t)
print(type(array_1d))
print(array_ld)

<class 'numpy.ndarray'>
[7 9 0 3 4]


In [0]:
d={1:1,2:4,3:9}
array_ld=np.array(list(d.values()))
array_ld

array([1, 4, 9])

#Initializing Arrays

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
array_zeros=np.zeros((3,3))
print(array_zeros.dtype)
print(type(array_zeros))

float64
<class 'numpy.ndarray'>


In [0]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    full : Return a new array of given shape filled with value.
    
 

In [0]:
array_zeros=np.zeros((3,3),dtype=int)
print(array_zeros.dtype)
print(type(array_zeros))
print(array_zeros)

int64
<class 'numpy.ndarray'>
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [0]:
array_ones=np.ones((3,3),dtype=int)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)

int64
<class 'numpy.ndarray'>
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [0]:
array_ones=np.ones((3,3),dtype=bool)
print(array_ones.dtype)
print(type(array_ones))
print(array_ones)

bool
<class 'numpy.ndarray'>
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [0]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [0]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Creating arrays with in a specific range

In [0]:
print(np.arange(6))
print(np.arange(1,6))
print(np.arange(1,6,2))
print(np.arange(1,6,0.5))
#print(list(range(1,6,0.5)))

[0 1 2 3 4 5]
[1 2 3 4 5]
[1 3 5]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5]


In [0]:
print(np.linspace(1,5,10))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [0]:
print(np.linspace(1,5,10))
print(np.linspace(1,5,3))
print(np.linspace(1,5,2))


[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 3. 5.]
[1. 5.]


In [0]:
np.random.randint(10) #output range 0 to 9

1

In [0]:
np.random.randint(10,size=(2,3))

array([[3, 6, 2],
       [5, 5, 8]])

In [0]:
np.random.randint(10,size=(2))

array([9, 2])

In [0]:
np.random.randint(10,34,size=(2))

array([14, 31])

In [0]:
multi_array = np.random.randint(1,1000,size=(10,10))
multi_array

array([[238, 492, 603, 664, 967, 886, 716, 893, 590, 981],
       [707, 980, 672, 430, 408, 241, 814, 229, 918, 372],
       [151, 776, 633, 700, 842, 499, 540, 903, 697, 423],
       [662, 479, 847, 872, 624, 116, 257, 820, 857, 750],
       [400, 779, 794,  18, 870, 374, 595, 737, 266, 671],
       [649, 325, 547, 602, 718, 885, 140, 102,  76, 868],
       [100, 439, 537, 747, 732, 722, 270, 160, 402, 780],
       [349, 164, 176, 702, 111, 992, 235, 972, 322, 412],
       [528, 279, 822, 172, 362, 487, 727,  26, 485, 462],
       [253, 597, 399, 454, 493, 483, 541, 657, 914, 860]])

In [0]:
array_1d,array_ones,array_zeros

(array([7, 9, 0, 3, 4]), array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]), array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

In [0]:
print(array_1d.dtype) # data type of the array
print(array_1d.shape) # shape as a tuple
print(array_1d.ndim) # no of dimensions
print(array_1d.size) # no of items in the array
print(array_1d.itemsize) # size in bytes
print(array_1d.nbytes) # itemsize * no of items

int64
(5,)
1
5
8
40


In [0]:
t= (5,)
print(t,type(t))

(5,) <class 'tuple'>


In [0]:
array_1d

array([7, 9, 0, 3, 4])

In [0]:
array_1d[1] = 3
array_1d

array([7, 3, 0, 3, 4])

In [0]:
array_zeros[0] =5
array_zeros

array([[5, 5, 5],
       [0, 0, 0],
       [0, 0, 0]])

In [0]:
# how to update the 2nd row 3rd element
array_zeros[1][2] = 6
array_zeros

array([[5, 5, 5],
       [0, 0, 6],
       [0, 0, 0]])

In [0]:
# check for loop with 1d and 2d arrays
for i in array_1d:
    print(i)
    break

7


In [125]:
for i in array_zeros:
    print(i)
    break

[5 5 5]


Mathematical operators

In [0]:
a=np.arange(1,11)
b=np.arange(10,20)
print(a+b)
print(a*b)
print(b/a)
print(b//a)
print(b%a)
print(a**b)

[11 13 15 17 19 21 23 25 27 29]
[ 10  22  36  52  70  90 112 136 162 190]
[10.          5.5         4.          3.25        2.8         2.5
  2.28571429  2.125       2.          1.9       ]
[10  5  4  3  2  2  2  2  2  1]
[0 1 0 1 4 3 2 1 0 9]
[                   1                 2048               531441
             67108864           6103515625         470184984576
       33232930569601     2251799813685248   150094635296999121
 -8446744073709551616]


In [0]:
print(a>5)
print(a==5)
print(a<5)

[False False False False False  True  True  True  True  True]
[False False False False  True False False False False False]
[ True  True  True  True False False False False False False]
