<a href="https://colab.research.google.com/github/PRihana/Machine-learning/blob/master/20_03_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy

  - convert A list,tuple,dict in to Numpy array
  - How to generate array with in a range of values
     - arange
     - linspace
     - random.randint
  - basic arthimetc operators on numpy array

In [1]:
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
# How to slicing 
print(a[1:10])
print(a[1:5:2])
print(a[:])

[1 2 3 4 5 6 7 8 9]
[1 3]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [4]:
# Fancy Indexing or Boolean Indexing
print(a[a>5])

[6 7 8 9]


In [5]:
a.shape

(10,)

In [6]:
a.ndim

1

In [7]:
a2 = np.random.randint(10,30,(3,3))
a2

array([[19, 15, 21],
       [15, 18, 13],
       [22, 26, 12]])

In [9]:
print(a2.ndim)
print(a2.shape)

2
(3, 3)


In [10]:
for i in a2:
    print(i)
    break

[19 15 21]


In [11]:
for i in a2:
    for j in i:
        print(j,end=' ')
    print()

19 15 21 
15 18 13 
22 26 12 


In [12]:
print(a2[0],type(a2[0]),a2[0].shape)

[19 15 21] <class 'numpy.ndarray'> (3,)


In [13]:
print(a2[1:],type(a2[1:]),a2[1:].shape)

[[15 18 13]
 [22 26 12]] <class 'numpy.ndarray'> (2, 3)


In [14]:
# rows from 0  to 2
# columns from 0 to 2
# 1st row and second column
print(a2[1][2])
print(a2[1,2])

13
13


In [15]:
print(a2[1:3])

[[15 18 13]
 [22 26 12]]


In [16]:
print(a2[1:3,0:2])

[[15 18]
 [22 26]]


In [17]:
print(a2)

[[19 15 21]
 [15 18 13]
 [22 26 12]]


In [18]:
a3 = np.random.randint(10,100,(5,5,3))
a3

array([[[55, 77, 12],
        [53, 30, 34],
        [70, 93, 13],
        [36, 18, 10],
        [74, 34, 26]],

       [[56, 11, 37],
        [12, 37, 80],
        [21, 68, 46],
        [13, 13, 81],
        [74, 73, 18]],

       [[46, 12, 79],
        [35, 71, 82],
        [61, 62, 85],
        [77, 28, 20],
        [13, 20, 30]],

       [[69, 68, 70],
        [69, 24, 58],
        [78, 12, 18],
        [65, 32, 14],
        [75, 52, 93]],

       [[57, 90, 23],
        [53, 70, 49],
        [34, 98, 56],
        [65, 90, 60],
        [15, 47, 61]]])

In [19]:
print(a3[:2]) # indices - 0,1

[[[55 77 12]
  [53 30 34]
  [70 93 13]
  [36 18 10]
  [74 34 26]]

 [[56 11 37]
  [12 37 80]
  [21 68 46]
  [13 13 81]
  [74 73 18]]]


In [20]:
print(a3[1::2])

[[[56 11 37]
  [12 37 80]
  [21 68 46]
  [13 13 81]
  [74 73 18]]

 [[69 68 70]
  [69 24 58]
  [78 12 18]
  [65 32 14]
  [75 52 93]]]


In [21]:
print(a3[1::2,2])

[[21 68 46]
 [78 12 18]]


In [22]:
print(a3[1::2,0:5:2])

[[[56 11 37]
  [21 68 46]
  [74 73 18]]

 [[69 68 70]
  [78 12 18]
  [75 52 93]]]


In [23]:
print(a3[1::2,0:5:2,2])

[[37 46 18]
 [70 18 93]]


In [24]:
a3==86

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])

In [26]:
# Boolean Indexing
a3[a3==86]

array([], dtype=int64)

In [27]:
a3[a3>50]

array([55, 77, 53, 70, 93, 74, 56, 80, 68, 81, 74, 73, 79, 71, 82, 61, 62,
       85, 77, 69, 68, 70, 69, 58, 78, 65, 75, 52, 93, 57, 90, 53, 70, 98,
       56, 65, 90, 60, 61])

In [28]:
a3[(a3>50) & (a3<70)] #or -- |

array([55, 53, 56, 68, 61, 62, 69, 68, 69, 58, 65, 52, 57, 53, 56, 65, 60,
       61])

In [29]:
a3[(a3<50) | (a3>70)]

array([77, 12, 30, 34, 93, 13, 36, 18, 10, 74, 34, 26, 11, 37, 12, 37, 80,
       21, 46, 13, 13, 81, 74, 73, 18, 46, 12, 79, 35, 71, 82, 85, 77, 28,
       20, 13, 20, 30, 24, 78, 12, 18, 32, 14, 75, 93, 90, 23, 49, 34, 98,
       90, 15, 47])

In [0]:
L = list(range(100))
# 0,1,2,3--- L[:]
# 1,2,3,4.... L[1:]
# 1,3,5,7,9,11,13 #L[1::2]
# 1,13,45,74,23,67 #

In [32]:
L[[1,13,45,74,23,67]]

TypeError: ignored

In [33]:
aL = np.array(L)
aL[[1,13,45,74,23,67]]

array([ 1, 13, 45, 74, 23, 67])

In [34]:
aL[[45,74,23,67,1,7,3]]

array([45, 74, 23, 67,  1,  7,  3])

In [35]:
a2

array([[19, 15, 21],
       [15, 18, 13],
       [22, 26, 12]])

In [36]:
a2[[1,2],[0,1]] # (1,0)(2,1)

array([15, 26])

In [37]:
print(a3[[1,2],[1,2],[1,2]])#(1,1,1)(2,2,2)
print(a3[1,1,1])
print(a3[2,2,2])

[37 85]
37
85


**statistical Functions**

In [90]:
a = np.random.randint(20,30,5)
a

array([27, 25, 27, 20, 22])

In [91]:
print(np.mean(a))# avg
print(np.sum(a)/np.size(a))

24.2
24.2


In [92]:
# sorted a[23,24,25,27,29]
np.median(a)

25.0

In [93]:
print(np.quantile(a,0.25)) # Q1
print(np.quantile(a,0.5)) # Q2
print(np.quantile(a,0.75)) # Q3

22.0
25.0
27.0


**Logorithemic and Exponential**

In [45]:
import numpy as np
print(np.log(2))# log with base e
print(np.log(np.exp(1)))

0.6931471805599453
1.0


In [46]:
print(np.log2(2))
print(np.log2(7))
print(np.log10(5))

1.0
2.807354922057604
0.6989700043360189


In [48]:
np.log(0+1)

0.0

In [49]:
print(np.log1p(2)) # np.log(1+2)
print(np.log1p(0)) # np.log(1+0)

1.0986122886681096
0.0


In [50]:
np.exp(1)

2.718281828459045

In [51]:
np.exp(2)

7.38905609893065

In [52]:
print(np.exp2(4))#2**4

16.0


In [53]:
print(np.expm1(2))# np.exp(2)-1
print(np.exp(2)-1)

6.38905609893065
6.38905609893065
