<a href="https://colab.research.google.com/github/PRihana/Machine-learning/blob/master/21_03_2020(ML)Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Import numpy as np and print the version number.
import numpy as np
print(np.__version__)

1.18.2


In [0]:
#Create a 1D array of numbers from 0 to 9
import numpy as np
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
#Create a 3×3 numpy array of all True’s
import numpy as np
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
#Extract all odd numbers from arr
l=np.arange(20)
print(l)
print(type(l))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [10]:
for i in l:
    if i%2!=0:
        print(i)
    else:
        pass

1
3
5
7
9
11
13
15
17
19


In [11]:
#Replace all odd numbers in arr with -1
for i in l:
    if i%2!=0:
        l[i]=-1
    else:
        pass
print(l)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [12]:
#Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [13]:
np.hstack(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.hstack(b)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [0]:
#Convert a 1D array to a 2D array with 2 rows
import numpy as np
Array1D = np.array([(5, 0, 380, 3)])
print(Array1D)
Array2D = Array1D.flatten()
print(Array2D)

[[  5   0 380   3]]
[  5   0 380   3]


In [15]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a)
print(b)

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]


In [16]:
for i in range(len(a)):
    if a[i]==b[i]:
        print(i,end=" ")

1 3 5 7 

In [18]:
#Get all items between 5 and 10 from a.
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(a)
for i in a:
    if i>5 and i<10:
        print(i)

[ 2  6  1  9 10  3 27]
6
9


In [19]:
#Write a NumPy program to generate five random numbers from the normal distribution
a=np.random.normal(size=5) # from normal distribution 
print(a)

[ 1.61059147  1.24837297  2.20334275 -2.31979365 -0.32953643]


In [20]:
#Write a NumPy program to generate six random integers between 10 and 30
b=np.random.randint(10,30,size=6)
print(b)

[18 12 12 14 19 20]


In [21]:
#Write a NumPy program to create a 3x3x3 array with random values
x=np.random.random((3,3,3))
print(x)

[[[0.37922359 0.53120111 0.38944887]
  [0.92110539 0.8077702  0.95540323]
  [0.24984184 0.62770507 0.79553364]]

 [[0.93019242 0.72574369 0.56236537]
  [0.90511781 0.09160464 0.64461211]
  [0.15924127 0.96740048 0.06171043]]

 [[0.6045261  0.81166175 0.03506053]
  [0.61581934 0.45836691 0.99525457]
  [0.8137967  0.2439536  0.44754747]]]


In [29]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values¶
s=np.random.random((5,5))
print(s)

[[0.72154177 0.52974249 0.60405533 0.99987484 0.78629136]
 [0.715811   0.69205707 0.89037773 0.32306774 0.51460604]
 [0.01455328 0.6531857  0.18103797 0.57656685 0.94093815]
 [0.79660491 0.14403012 0.52049169 0.97355985 0.64375165]
 [0.87131729 0.04006934 0.7487122  0.63783636 0.44871634]]


In [30]:
np.max(s)

0.9998748427368671

In [31]:
np.min(s)

0.01455327535465789

In [32]:
#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variables
a=np.random.random((10,4))
print(a)

[[0.7274961  0.30252133 0.27752816 0.07452802]
 [0.80595407 0.87373847 0.05946466 0.76870094]
 [0.28069733 0.96694654 0.88730474 0.32603901]
 [0.50304563 0.81537631 0.49345743 0.12675382]
 [0.76467253 0.13391741 0.22632064 0.75491064]
 [0.50398612 0.63011115 0.27919464 0.20490143]
 [0.08973377 0.03009199 0.60950787 0.80103427]
 [0.31975575 0.72774013 0.39316414 0.25364438]
 [0.2998747  0.70585904 0.01537534 0.12439798]
 [0.43516789 0.10845027 0.49054446 0.88453236]]


In [33]:
h=a[0:5,:]
print(h)

[[0.7274961  0.30252133 0.27752816 0.07452802]
 [0.80595407 0.87373847 0.05946466 0.76870094]
 [0.28069733 0.96694654 0.88730474 0.32603901]
 [0.50304563 0.81537631 0.49345743 0.12675382]
 [0.76467253 0.13391741 0.22632064 0.75491064]]


In [0]:
#Write a NumPy program to shuffle numbers between 0 and 10 (inclusive)

In [34]:
x = np.arange(10)
print(x)
np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[8 0 4 3 9 1 6 2 7 5]


In [0]:
#Stack arrays a and b vertically
import numpy as np  
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)  
# Stacking the two arrays vertically 
out_arr = np.vstack((a,b)) 
print ("Output vertically stacked array:\n ", out_arr) 

Output vertically stacked array:
  [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [0]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.hstack((a,b))

array([ 1,  2,  3,  2,  3,  4,  3,  4,  5,  6,  7,  2, 10,  2,  7,  4,  9,
        4,  9,  8])

In [0]:
#swap columns 1 and 2 in the array arr.
import numpy as np
arr = np.arange(9).reshape(3,3)
print("Original array:")
print(arr)
arr[:,[0, 1]] = arr[:,[1, 0]]
print("\nAfter swapping arrays:")
print(arr)

Original array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

After swapping arrays:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [6]:
#How to reverse to the rows of a 2D aray
import numpy as np
arr = np.arange(9).reshape(3,3) 
print(arr)
reversedArr = np.flip(arr, axis=0) 
print('Reversed Array : ')
print(reversedArr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed Array : 
[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [8]:
#How to reverse to the columns of a 2D aray
import numpy as np
arr = np.arange(9).reshape(3,3) 
print(arr)
reversedArr = np.flip(arr, axis=1) 
print('Reversed Array : ')
print(reversedArr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Reversed Array : 
[[2 1 0]
 [5 4 3]
 [8 7 6]]
